### ISSUE TITLE
Update Instantiate() in known_truth.py to accept a RoToR for a repl_map key

### ISSUE THREAD

**Issue by jmadridlarra** [PyProveIt/Prove-It#166]
When trying to instantiate an ExprTuple of an ExprRange of an ExprRange (RoToR) of IndexedVars, instantiate() in known_truth.py throws an error:

`(A_{1,1}, ..A_{1,j}.., A_{1,k}, ....A_{i,1}, ..A_{i,j}.., A_{i,k}...., A_{m,1}, ..A_{m,j}.., A_{m,k}) is not the expected kind of Expression as a repl_map key.  An ExprTuple with one entry is expected to contain an ExprRange of IndexedVars. `

This should be relaxed to allow a RoToR of IndexedVars because of the requirements involving ExprArrays which often contain RoToRs.  Change around line 812 in known_truth.py

**Comment by wwitzel** [comment]
I'll take care of this right now.  I think I know what to do.  I'll use the getParamVar method in Lambda.

**Comment by wwitzel** [comment]
@jmadridlarra : Try pulling in the branch: 166-instantiate-with-range-of-range-key and let me know if that works for you.

**Comment by jmadridlarra** [comment]
@wwitzel Now I'm getting an assertion error in proof.py:

```
c:\users\joaqu\prove-it\packages\proveit\_core_\proof.py in __init__(self, orig_known_truth, num_forall_eliminations, repl_map, equiv_alt_expansions, assumptions)
    880                 # KnownTruth.instantiate:
    881                 assert (len(key)==1 and isinstance(key[0], ExprRange) 
--> 882                     and isinstance(key[0].body, IndexedVar))
    883                 parameters.append(key[0])
    884             else:
```

I think these are along the same vein.  It seems like it's still looking for a Range of an IndexedVar rather than a Range of a Range of an IndexedVar

**Comment by wwitzel** [comment]
Yeah, okay, I'm on it.

**Comment by wwitzel** [comment]
Try it now.

**Comment by jmadridlarra** [comment]
Now it's trying to iterate over the circuit... is this what we want?
```
c:\users\joaqu\prove-it\packages\proveit\_core_\proof.py in __init__(self, orig_known_truth, num_forall_eliminations, repl_map, equiv_alt_expansions, assumptions)
    912                     # Yield the entries for the replacement of the
    913                     # ExprTuple of the parameter.
--> 914                     for entry in repl_map[ExprTuple(parameter)]:
    915                         operands.append(entry)
    916                 else:

TypeError: 'Circuit' object is not iterable
```

**Comment by wwitzel** [comment]
Provide more debugging info.  Can you print out 'instantiation_params' and 'instantiation_param_vars' before it raises this exception?

**Comment by wwitzel** [comment]
Or maybe just print out their types.

**Comment by jmadridlarra** [comment]
This is the full trace back, but the error is getting raised before instantiation_params and instantiation_param_vars are defined.  (They are used in the _instantiated_expr method which is first called on line 941 and the error is on line 914). 

The problem is because the for loop is trying to loop over the circuit element, but it can't... it needs to loop over circuit.entries() for it to work.  That's why I asked if the circuit is in the right place, should it be wrapped in a list instead?  

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-19ae8d47da06> in <module>
      4                               ExprTuple(varRange(S, one, m)): ExprTuple({one, two}, {one, two}),
      5                               ExprTuple(varRange(R, [one, one], [m, k])): ExprTuple(),
----> 6                               ExprTuple(varRange(Q, [one, one], [m, h])): ExprTuple()}, assumptions=[CircuitEquiv(lhs, rhs)])

c:\users\joaqu\prove-it\packages\proveit\_core_\known_truth.py in specialize(self, repl_map, relabel_map, assumptions)
    735         if relabel_map is not None:
    736             repl_map.update(relabel_map)
--> 737         return self.instantiate(repl_map, assumptions=assumptions)
    738 
    739 

c:\users\joaqu\prove-it\packages\proveit\_core_\known_truth.py in instantiate(self, repl_map, num_forall_eliminations, assumptions)
    893                               repl_map=processed_repl_map,
    894                               equiv_alt_expansions=equiv_alt_expansions,
--> 895                               assumptions=assumptions))
    896 
    897     def generalize(self, forall_var_or_vars_or_var_lists, 

c:\users\joaqu\prove-it\packages\proveit\_core_\proof.py in __init__(self, orig_known_truth, num_forall_eliminations, repl_map, equiv_alt_expansions, assumptions)
    912                     # Yield the entries for the replacement of the
    913                     # ExprTuple of the parameter.
--> 914                     for entry in repl_map[ExprTuple(parameter)]:
    915                         operands.append(entry)
    916                 else:

TypeError: 'Circuit' object is not iterable
```

**Comment by wwitzel** [comment]
I'd like to see the full repl_map dictionary  ExprTuples should be replaced with ExprTuples.  This error suggests that an ExprTuple is being replaced by a Circuit which is not an ExprTuple.  You probably need to grab the ".array" of the Circuit.  I'll try to remember to make a more appropriate error message about replacing ExprTuples with ExprTuples in this branch while we are at it.

**Comment by wwitzel** [comment]
It occurred to me that you should linearize the "array" when you make it a replacement.  That is, you'll need to convert it from an ExprTuple of ExprTuples to just a 1D ExprTuple since the parameters are 1D.  For example:
[[A, B, C], [D, E, F]] would "linearize" to
[A, B, C, D, E, F]

Try it without linearizing it first to see what error message you get and show me the trace back.  We'll want to make a proper error message for that instance.  Then work to make a ".flat()" method for ExprArray which will return a linearized version so you can pass is ".array.flat()" for the replacement.

We'll get there.  I had a feeling it wouldn't quite work without some tweaks since this is uncharted territory.

**Comment by jmadridlarra** [comment]
I went back through the input cell and I discovered that one of the inputs was NOT wrapped in a Tuple, that seemed to fix that problem from yesterday.  I had to rerun several theorem/axiom notebooks because of the rebasing from yesterday which took a while this morning.  I had already been "flattening" the inputs manually, but I agree that a .flat() method is necessary.  Below is the error output from an unflattened input.  (I assumed the inputs should just be the contents of the ExprArray, without the circuit wrapping, but correct me if I'm wrong).  Interestingly, this is the same error as the flattened input.  Unfortunately, I am having to par down my expressions because Prove-It is having trouble counting past 10.  It counts all of the inputs and if there are more than 10, it throws an error-a different, but related problem.   

```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in extract_param_replacements(parameters, parameter_vars, body, operands_iter, assumptions, requirements, repl_map, is_complete)
   1137                                 break # we have a match
-> 1138                         operand_entry = next(operands_iter)
   1139                         param_operands.append(operand_entry)

StopIteration: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in extract_complete_param_replacements(parameters, parameter_vars, body, operands, assumptions, requirements, repl_map)
   1030                                    operands_iter, assumptions, requirements,
-> 1031                                    repl_map, is_complete=True)
   1032     except ValueError as e:

c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in extract_param_replacements(parameters, parameter_vars, body, operands_iter, assumptions, requirements, repl_map, is_complete)
   1204                          "or unproven length equality for "
-> 1205                          "correspondence with %s."%str(parameter))
   1206 

ValueError: Parameter/argument length mismatch or unproven length equality for correspondence with A_{1,1}, ..A_{1,j}.., A_{1,k}, ....A_{i,1}, ..A_{i,j}.., A_{i,k}...., A_{m,1}, ..A_{m,j}.., A_{m,k}.

During handling of the above exception, another exception occurred:

LambdaApplicationError                    Traceback (most recent call last)
c:\users\joaqu\prove-it\packages\proveit\_core_\proof.py in __init__(self, orig_known_truth, num_forall_eliminations, repl_map, equiv_alt_expansions, assumptions)
    947                         assumptions, requirements,
--> 948                         equality_repl_requirements)
    949 

c:\users\joaqu\prove-it\packages\proveit\_core_\proof.py in _instantiated_expr(original_known_truth, num_forall_eliminations, instantiation_params, repl_map, equiv_alt_expansions, assumptions, requirements, equality_repl_requirements)
   1218                 # Instantiate the condition.
-> 1219                 subbed_cond = instantiate(condition)
   1220                 if isinstance(subbed_cond, And):

c:\users\joaqu\prove-it\packages\proveit\_core_\proof.py in instantiate(expr, exclusion)
   1166                     assumptions=assumptions, requirements=requirements,
-> 1167                     equality_repl_requirements=equality_repl_requirements)    
   1168 

c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in _apply(parameters, body, equiv_alt_expansions, allow_relabeling, assumptions, requirements, equality_repl_requirements, parameter_vars, *operands)
    515                 parameters, parameter_vars, body, operands,
--> 516                 assumptions, requirements, repl_map)
    517 

c:\users\joaqu\prove-it\packages\proveit\_core_\expression\lambda_expr\lambda_expr.py in extract_complete_param_replacements(parameters, parameter_vars, body, operands, assumptions, requirements, repl_map)
   1033         raise LambdaApplicationError(
-> 1034                 parameters, body, operands, assumptions, [], str(e))
   1035 

LambdaApplicationError: Failure to apply (h, k, m, A_{1,1}, ..A_{1,j}.., A_{1,k}, ....A_{i,1}, ..A_{i,j}.., A_{i,k}...., A_{m,1}, ..A_{m,j}.., A_{m,k}, B_{1}, ..B_{_a}.., B_{m}, C_{1,1}, ..C_{1,_b}.., C_{1,h}, ....C_{_a,1}, ..C_{_a,_b}.., C_{_a,h}...., C_{m,1}, ..C_{m,_b}.., C_{m,h}, D_{1}, ..D_{_a}.., D_{m}, S_{1}, ..S_{_a}.., S_{m}, R_{1,1}, ..R_{1,_b}.., R_{1,k}, ....R_{_a,1}, ..R_{_a,_b}.., R_{_a,k}...., R_{m,1}, ..R_{m,_b}.., R_{m,k}, Q_{1,1}, ..Q_{1,_b}.., Q_{1,h}, ....Q_{_a,1}, ..Q_{_a,_b}.., Q_{_a,h}...., Q_{m,1}, ..Q_{m,_b}.., Q_{m,h}) -> ((h in NaturalsPos) and (k in NaturalsPos) and (m in NaturalsPos)) to (1, 1, 1, ([GATE](H)), ([GATE](Z)), ([GATE](X)), ([GATE](Z)), (), (), ()) assuming ( [GATE](Z) equiv  [GATE](Z),):
Parameter/argument length mismatch or unproven length equality for correspondence with A_{1,1}, ..A_{1,j}.., A_{1,k}, ....A_{i,1}, ..A_{i,j}.., A_{i,k}...., A_{m,1}, ..A_{m,j}.., A_{m,k}.

During handling of the above exception, another exception occurred:

InstantiationFailure                      Traceback (most recent call last)
<ipython-input-22-5d0b89effbb1> in <module>
      8                               ExprTuple(varRange(R, [one, one], [m, k])): ExprTuple({}),
      9                               ExprTuple(varRange(Q, [one, one], [m, h])): ExprTuple({})}, 
---> 10                              assumptions=[CircuitEquiv(Circuit(ExprArray(ExprTuple(Gate(Z)))), Circuit(ExprArray(ExprTuple(Gate(Z)))))])

c:\users\joaqu\prove-it\packages\proveit\_core_\known_truth.py in specialize(self, repl_map, relabel_map, assumptions)
    735         if relabel_map is not None:
    736             repl_map.update(relabel_map)
--> 737         return self.instantiate(repl_map, assumptions=assumptions)
    738 
    739 

c:\users\joaqu\prove-it\packages\proveit\_core_\known_truth.py in instantiate(self, repl_map, num_forall_eliminations, assumptions)
    893                               repl_map=processed_repl_map,
    894                               equiv_alt_expansions=equiv_alt_expansions,
--> 895                               assumptions=assumptions))
    896 
    897     def generalize(self, forall_var_or_vars_or_var_lists, 

c:\users\joaqu\prove-it\packages\proveit\_core_\proof.py in __init__(self, orig_known_truth, num_forall_eliminations, repl_map, equiv_alt_expansions, assumptions)
   1028         except LambdaApplicationError as e:
   1029             raise InstantiationFailure(orig_known_truth, repl_map,
-> 1030                                        assumptions, str(e))
   1031         finally:
   1032             # restore the original default assumptions

InstantiationFailure: Proof step failed assuming { [GATE](Z) equiv  [GATE](Z)}:
Attempting to instantiate |- forall_{h in NaturalsPos, k in NaturalsPos, m in NaturalsPos} [forall_{A_{1,1}, ..A_{1,_b}.., A_{1,k}, ....A_{_a,1}, ..A_{_a,_b}.., A_{_a,k}...., A_{m,1}, ..A_{m,_b}.., A_{m,k}, B_{1}, ..B_{_a}.., B_{m}, C_{1,1}, ..C_{1,_b}.., C_{1,h}, ....C_{_a,1}, ..C_{_a,_b}.., C_{_a,h}...., C_{m,1}, ..C_{m,_b}.., C_{m,h}, D_{1}, ..D_{_a}.., D_{m}, S_{1}, ..S_{_a}.., S_{m}, R_{1,1}, ..R_{1,_b}.., R_{1,k}, ....R_{_a,1}, ..R_{_a,_b}.., R_{_a,k}...., R_{m,1}, ..R_{m,_b}.., R_{m,k}, Q_{1,1}, ..Q_{1,_b}.., Q_{1,h}, ....Q_{_a,1}, ..Q_{_a,_b}.., Q_{_a,h}...., Q_{m,1}, ..Q_{m,_b}.., Q_{m,h}} (( B_{1} MULTI_QUBIT_GATE S_{1}   \\ 
   \colon   \\ 
   B_{i} MULTI_QUBIT_GATE S_{i}   \\ 
   \colon   \\ 
   B_{m} MULTI_QUBIT_GATE S_{m} equiv  D_{1} MULTI_QUBIT_GATE S_{1}   \\ 
   \colon   \\ 
   D_{i} MULTI_QUBIT_GATE S_{i}   \\ 
   \colon   \\ 
   D_{m} MULTI_QUBIT_GATE S_{m}) =>  \\ ( A_{1,1} MULTI_QUBIT_GATE R_{1,1}  & ..A_{1,j} MULTI_QUBIT_GATE R_{1,j}..  & A_{1,k} MULTI_QUBIT_GATE R_{1,k}  & B_{1} MULTI_QUBIT_GATE S_{1}  & C_{1,1} MULTI_QUBIT_GATE Q_{1,1}  & ..C_{1,j} MULTI_QUBIT_GATE Q_{1,j}..  & C_{1,h} MULTI_QUBIT_GATE Q_{1,h}   \\ 
   \colon  & \colon  & \colon  & \colon  & \colon  & \colon  & \colon   \\ 
   A_{i,1} MULTI_QUBIT_GATE R_{i,1}  & ..A_{i,j} MULTI_QUBIT_GATE R_{i,j}..  & A_{i,k} MULTI_QUBIT_GATE R_{i,k}  & B_{i} MULTI_QUBIT_GATE S_{i}  & C_{i,1} MULTI_QUBIT_GATE Q_{i,1}  & ..C_{i,j} MULTI_QUBIT_GATE Q_{i,j}..  & C_{i,h} MULTI_QUBIT_GATE Q_{i,h}   \\ 
   \colon  & \colon  & \colon  & \colon  & \colon  & \colon  & \colon   \\ 
   A_{m,1} MULTI_QUBIT_GATE R_{m,1}  & ..A_{m,j} MULTI_QUBIT_GATE R_{m,j}..  & A_{m,k} MULTI_QUBIT_GATE R_{m,k}  & B_{m} MULTI_QUBIT_GATE S_{m}  & C_{m,1} MULTI_QUBIT_GATE Q_{m,1}  & ..C_{m,j} MULTI_QUBIT_GATE Q_{m,j}..  & C_{m,h} MULTI_QUBIT_GATE Q_{m,h} equiv  A_{1,1} MULTI_QUBIT_GATE R_{1,1}  & ..A_{1,j} MULTI_QUBIT_GATE R_{1,j}..  & A_{1,k} MULTI_QUBIT_GATE R_{1,k}  & D_{1} MULTI_QUBIT_GATE S_{1}  & C_{1,1} MULTI_QUBIT_GATE Q_{1,1}  & ..C_{1,j} MULTI_QUBIT_GATE Q_{1,j}..  & C_{1,h} MULTI_QUBIT_GATE Q_{1,h}   \\ 
   \colon  & \colon  & \colon  & \colon  & \colon  & \colon  & \colon   \\ 
   A_{i,1} MULTI_QUBIT_GATE R_{i,1}  & ..A_{i,j} MULTI_QUBIT_GATE R_{i,j}..  & A_{i,k} MULTI_QUBIT_GATE R_{i,k}  & D_{i} MULTI_QUBIT_GATE S_{i}  & C_{i,1} MULTI_QUBIT_GATE Q_{i,1}  & ..C_{i,j} MULTI_QUBIT_GATE Q_{i,j}..  & C_{i,h} MULTI_QUBIT_GATE Q_{i,h}   \\ 
   \colon  & \colon  & \colon  & \colon  & \colon  & \colon  & \colon   \\ 
   A_{m,1} MULTI_QUBIT_GATE R_{m,1}  & ..A_{m,j} MULTI_QUBIT_GATE R_{m,j}..  & A_{m,k} MULTI_QUBIT_GATE R_{m,k}  & D_{m} MULTI_QUBIT_GATE S_{m}  & C_{m,1} MULTI_QUBIT_GATE Q_{m,1}  & ..C_{m,j} MULTI_QUBIT_GATE Q_{m,j}..  & C_{m,h} MULTI_QUBIT_GATE Q_{m,h}))] with {h: 1, k: 1, m: 1, (A_{1,1}, ..A_{1,j}.., A_{1,k}, ....A_{i,1}, ..A_{i,j}.., A_{i,k}...., A_{m,1}, ..A_{m,j}.., A_{m,k}): (([GATE](H))), (B_{1}, ..B_{_a}.., B_{m}): (([GATE](Z))), (C_{1,1}, ..C_{1,_b}.., C_{1,h}, ....C_{_a,1}, ..C_{_a,_b}.., C_{_a,h}...., C_{m,1}, ..C_{m,_b}.., C_{m,h}): (([GATE](X))), (D_{1}, ..D_{_a}.., D_{m}): (([GATE](Z))), (S_{1}, ..S_{_a}.., S_{m}): (()), (R_{1,1}, ..R_{1,_b}.., R_{1,k}, ....R_{_a,1}, ..R_{_a,_b}.., R_{_a,k}...., R_{m,1}, ..R_{m,_b}.., R_{m,k}): (()), (Q_{1,1}, ..Q_{1,_b}.., Q_{1,h}, ....Q_{_a,1}, ..Q_{_a,_b}.., Q_{_a,h}...., Q_{m,1}, ..Q_{m,_b}.., Q_{m,h}): (())}:
Failure to apply (h, k, m, A_{1,1}, ..A_{1,j}.., A_{1,k}, ....A_{i,1}, ..A_{i,j}.., A_{i,k}...., A_{m,1}, ..A_{m,j}.., A_{m,k}, B_{1}, ..B_{_a}.., B_{m}, C_{1,1}, ..C_{1,_b}.., C_{1,h}, ....C_{_a,1}, ..C_{_a,_b}.., C_{_a,h}...., C_{m,1}, ..C_{m,_b}.., C_{m,h}, D_{1}, ..D_{_a}.., D_{m}, S_{1}, ..S_{_a}.., S_{m}, R_{1,1}, ..R_{1,_b}.., R_{1,k}, ....R_{_a,1}, ..R_{_a,_b}.., R_{_a,k}...., R_{m,1}, ..R_{m,_b}.., R_{m,k}, Q_{1,1}, ..Q_{1,_b}.., Q_{1,h}, ....Q_{_a,1}, ..Q_{_a,_b}.., Q_{_a,h}...., Q_{m,1}, ..Q_{m,_b}.., Q_{m,h}) -> ((h in NaturalsPos) and (k in NaturalsPos) and (m in NaturalsPos)) to (1, 1, 1, ([GATE](H)), ([GATE](Z)), ([GATE](X)), ([GATE](Z)), (), (), ()) assuming ( [GATE](Z) equiv  [GATE](Z),):
Parameter/argument length mismatch or unproven length equality for correspondence with A_{1,1}, ..A_{1,j}.., A_{1,k}, ....A_{i,1}, ..A_{i,j}.., A_{i,k}...., A_{m,1}, ..A_{m,j}.., A_{m,k}.
```

**Comment by wwitzel** [comment]
Joaquin encountered further issues which relate to presuming parameters to be flat (rather than nested) ExprRanges in "extract_param_replacements" function of lambda_expr.py.  Specifically, min_int_param_operands_len and max_int_param_operads_len (used to speed up the process for instances when ranges have known integer extents) is wrong when ExprRanges are nested.  I'll try to fix this now (in the 166-... branch).

**Comment by wwitzel** [comment]
Done.  See if that fixes your problem, @jmadridlarra .

**Comment by jmadridlarra** [comment]
Same or Related issue: 

When trying to specialize an expression that contains a varRange, extract_param_replacements() in lambda_expr.py has trouble counting the number of values for the repl_map dictionary correctly. 

![image](https://user-images.githubusercontent.com/51240353/89470028-0299dd80-d738-11ea-8bfc-bd45216c487b.png)

In this example -- taken from a proof notebook--, extract_param_replacements() is throwing an error because it is correctly counting that there are too many values... but the extra value was not supposed to be subbed into the varRange. 

Interestingly, when the same expression is put into a demonstrations notebook, a proof is generated:

![image](https://user-images.githubusercontent.com/51240353/89470256-9cfa2100-d738-11ea-9bde-87b20ca06ba7.png)

Upon closer inspection, it seems like this could be because the proof in the demonstrations notebook is using proveit.number.numeral.deci._theorems_.tuple_len_2_typical_equiv (line 4).  The proof for tuple_len_2 is unable to presume tuple_len_2_typical_equiv to avoid a circular dependency problem.  This may explain why we are able to successfully complete a proof for an expression when a similar expression throws this error.  

It seems like this issue has something to do with when extract_param_replacements() counts the "operands" to sub into the expression.  It knows when there are too many, but it doesn't know to stop adding "operands" to the list once it's reached the number of operands the varRange key has. Does that make sense?

**Comment by wwitzel** [comment]
Ah!  This is a different issue than I thought it was @jmadridlarra .  It's actually not related to this issue (as I had thought).  But that's okay.  It's a dependencies issue.  A theorem cannot depend upon another theorem that comes after it in the theorem's notebook.  Your tuple_len_2 requires tuple_len_1_typical_equiv.  tuple_len_3 requires tuple_len_2_typical_equiv.  And so forth.  The tricky thing is that we may need to have tuple_len_1_typical_equiv depend upon tuple_len_1, tuple_len_2_typical_equiv depend upon tuple_len_2, etc.  Actually, the "count_to_range" ones should be in the mix as well.  I'm not sure.  If that's the case, we'd need to collate them which would be a little tricky given the way I generated them in the theorems page.  But if they don't have those dependencies, you could just move the tuple_len_n_typical_equiv theorems above the tuple_len_n theorems.  Think about it.  I haven't thought about it much yet.  Note, you have to rerun the full theorems notebook after you reorder the theorems for it to take effect.

**Comment by jmadridlarra** [comment]
While I am happy to try rearranging the theorems and/or collate them, it seems like the order as it stands is what we want (tuple_len_n, then typical_equiv, lastly count_to_range).  While using the typical_equiv theorems might make the "tuple_len" theorems shorter, I think we need the "tuple_len" theorems to prove the typical_equiv theorems and then I think we would need the typical_equiv theorems to prove the count_to_range.  Right now I don't see how to prove the typical_equiv theorems without the tuple_len theorems, but let me know if you can see another way.  (For now I can try rearranging them and continuing on as planned, but these are my thoughts before moving ahead)

On another note, while rearranging the theorems might avoid running into the lambda_expr error for this specific instance, it still doesn't fix it.  I'm running into this error when I am specializing tuple_len_incr in the demonstrations notebook as well as in the circuit demonstrations notebook, both of which don't depend on theorem ordering, correct?

**Comment by jmadridlarra** [comment]
Rearranging the theorems seemed to avoid this issue in the proof notebooks. However, I am still getting the same error in the numeral.deci._demonstrations_ notebook when I specialize:

![image](https://user-images.githubusercontent.com/51240353/89683315-904f0780-d8b5-11ea-8b49-e36d3f00bac6.png)

And in the circuit _demonstrations_ notebook (the original error that prompted the creation of this issue):

![image](https://user-images.githubusercontent.com/51240353/89683432-c1c7d300-d8b5-11ea-9f68-e6faf24c9b30.png)

There is more to the error output which I can add if you would like, but it follows along the lines of "During handling of the above exception, another exception occurred:" and they are all lamdaApplication errors or Instantiation errors.

**Comment by wwitzel** [comment]
This looks like a "counting past 10" issue which is why you starting working on counting past 10 in the first place.  I know the error is confusing, but I think that's what it is.  Or do you think it is something else/more?

**Comment by jmadridlarra** [comment]
It could be a counting past 10 issue, but I've implemented machinery to count past 10 and I was testing it when I got the first error.  One thing that makes me think that it is not counting past 10 is the second error which only has 4 inputs.  

The issue is that an extra argument is being added to the arguments list.  The error is valid (in the first error there are 12 arguments in the list when there should be 11 and in the second error there are 5 when there should be 4).  Prove-It is correctly raising an error, but the problem is that Prove-It also accidentally adding an extra argument which causes the error to be thrown.  It is possible that I am missing something so do let me know if this is just a counting issue, but it seems to be more.

**Comment by wwitzel** [comment]
You have to recognize that Prove-It isn't counting in a "normal" python way for this.  It has to "prove" the counting, and if it is unable to do so for whatever reason, it ends up looking a bit foolish w.r.t. this error.  I'll try to take a closer look after the meeting.  I'll switch to your branch and try to run it.  Make sure you push everything I need to test this. Thanks.

**Comment by jmadridlarra** [comment]
Right, the machinery in place is supposed to use tuple_len_incr as well as md_nine_add_one to prove the counting, but I wanted to test it explicitly in the demonstrations notebook before testing the method itself.  However, I just realized Prove-It uses the machinery I was testing to specialize tuple_len_incr and that is likely why the error is being thrown.  Unfortunately, this makes it rather hard to test (and might cause an infinite loop?  I'd have to think about that further though).  The first error and the counting machinery is in the **137-Multi-digit_arithmetic** branch where the counting machinery (which is not finished-I was in the process of testing when I got this error) is in length.py on line 116. 

If this was the only error, I would be fine with accepting that the counting is the error and moving forward.  However, I don't see how the circuit error (which is in branch **142-Quantum_circuit_v3** in circuit._demonstrations_ cell 14) is having issues counting past 10 when it only has four arguments.  I did pull in your edits from the 166-instantiate-with-range-of-range-key branch into the quantum circuit branch which I think makes sure that the range of range is counted correctly, but it could be that the range of range counting is contributing to the error in Quantum Circuit and it just so happens that this quantum circuit issue is coincidentally throwing the same error as the counting issue above.  

Feel free to look at the machinery for counting in 137-Multi-digit_arithmetic, but I'm going to take a closer look myself because I didn't realize tuple_len_incr is utilizing that method to specialize.  However, I think it would be more useful to take a look at the circuit error since I really don't understand why that error is being thrown.

**Comment by wwitzel** [comment]
I looking into the error you get in 142-Quantum_circuit_v3. The problem is that Prove-It does not know how to evaluate the length of a range of ranges and construct the proof.  With 166-instantiate-with-range-of-range-key, it will compute it for the special case when the start and end indices of the ranges are integers.  However, it isn't actually proving that, it is just using that information as a useful hint.  It needs to be able to prove it.  But there isn't even an axiom for it to know what the length of a range of ranges should be.  And then, what about a range of ranges of ranges?  Maybe we don't want to bother supporting that.  In any case, I need to think about it a little.  I hope to have a solution for you soon.

**Comment by wwitzel** [comment]
I take that back.  It is set up to use the "general_len" conjecture (whether this can be proven via the axioms we have is not clear to me at the moment, but that's an issue for another time).  Your problem is that you've disabled automation in your notebook for whatever reason.

**Comment by wwitzel** [comment]
@jmadridlarra : Pull 172-variable-bug-fixes.  That should fix that problem.  Sorry it took me a little while.  While my first fix eliminated the problem, I didn't fully understand why it eliminated the problem until I discovered a second bug.

**Comment by wwitzel** [comment]
Addressed via 166-instantiate-with-range-of-range-key
